### ISSUE TITLE
stop lag generate?

### ISSUE THREAD

**Issue by BabelSolea** [RienBijl/Scoreboard#2]
my situation example:
1200ticks * 15 lines * some players = freeze server after 1-2 hours with 10- players!!!
1. useless update line every 1200 ticks: 1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15 = 11/15 lines
11/15 lines per player dont need upd ever.

11 lines per player - that lag generator i cant continue using this plugin.
what i can put in "update: ???" to stop updates this string? "-1" is ok?

and is it possible to update placeholder only when that placeholder really changed?

  '1':
    content:
      - '&aSiacraft 2.0'
    update: 1200
  '2':
    content:
      - ''
    update: 1200
  '3':
    content:
      - '&etext:'
    update: 1200
  '4':
    content:
      - '&f%vault_eco_balance% &e$'
    update: 1200
  '5':
    content:
      - ''
    update: 1200
  '6':
    content:
      - '&3SIA-text'
    update: 1200
  '7':
    content:
      - '&f%tokenmanager_tokens% &3✪'
    update: 1200
  '8':
    content:
      - ''
    update: 1200
  '9':
    content:
      - '&6text'
    update: 1200
  '10':
    content:
      - '&f%mysteryboxes_amount_sq1%'
    update: 1200
  '11':
    content:
      - ''
    update: 1200
  '12':
    content:
      - '&6text'
    update: 1200
  '13':
    content:
      - '&f%proquests_total_points%'
    update: 1200
  '14':
    content:
      - ''
    update: 1200
  '15':
    content:
      - '&etext&a /menu '
    update: 1200

**Comment by RienBijl** [comment]
Branch scoreboardv2 has a *single* line generator per board, and not per player. It processes the placeholders after it gets the lines from the running board instance, will compare it to the most recent version and decide if it should update the board.
As for the loop, the current system *requires* a 1tick loop, because otherwise it would affect the 'update' parameter in the board instance.

Thanks for your imput! :)

**Comment by BabelSolea** [comment]
aneway i cant use placehoders in scoreboard cuz that eat RAM and proc until server fully freeze.

i show only link to site now cuz of that -_-
