### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by T1MOXA** [RienBijl/Scoreboard#3]
![image](https://user-images.githubusercontent.com/19938629/27501546-bed2b04c-5876-11e7-9d80-08c5b87473fb.png)
Last symbol is purple but must be white
` - ' &l%statistic_time_played%'`

![image](https://user-images.githubusercontent.com/19938629/27501601-058fbb10-5877-11e7-85d5-742c9a2f4aa2.png)
Player disconnect on line 
`- ' &fYour Ping - &c&l%player_ping% &fms.'`

**Comment by RienBijl** [comment]
Fixed in branch scoreboardv2, scheduled for next release.
